### PR TITLE
Fix grammar

### PR DESCRIPTION
**Pull request by axsuul**
Sorry, it irked me!

### CODE REVIEW

**Comment by lox** [comment]
Consider yourself now duty bound to provide some quality technical feedback as well:

http://blog.sandglaz.com/30-percent-feedback-rule/

**Comment by axsuul** [comment]
Shouldn't this "just work" with something like vagrant? That is, vagrant implements the protocol and watchers like guard can just tap into it? Having to run something third party behind the scenes on the host machine seems a little fragile to me.

**Comment by axsuul** [comment]
I guess what I'm saying is, this should probably be implemented on the VM/docker level where its a standard protocol... or perhaps some sort platform for sending file events is implemented at that layer. I too am frustrated with the current solutions out there and it's about time something "just works".

**Comment by lox** [comment]
Something like this? https://github.com/zaius/vagrant-listen-server

The issue is that injecting events into the VM/docker layer isn't easy, and possibly isn't possible. At the very least it would require a kernel module.

**Pull request merged**
